name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }] # Runs every midnight
  workflow_dispatch: # Allows you to run it manually
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RedtRocks
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          config_timezone: Asia/Kolkata
